name: HalosFirstPlugin
version: '${version}'
main: com.halosdev.halosfirstplugin.Main
api-version: '1.20'

commands:
  heal:
    description: Heal Command
  hello:
    description: Says Hello.
  console:
    description: A console Command.
  config:
    description: Config Command.
  word:
    description: Set a word value in the config